
//input ports
add mapped point clk_i clk_i -type PI PI
add mapped point rst_n_i rst_n_i -type PI PI
add mapped point alu_operation_id_i[3] alu_operation_id_i[3] -type PI PI
add mapped point alu_operation_id_i[2] alu_operation_id_i[2] -type PI PI
add mapped point alu_operation_id_i[1] alu_operation_id_i[1] -type PI PI
add mapped point alu_operation_id_i[0] alu_operation_id_i[0] -type PI PI
add mapped point alu_result_mux_id_i[2] alu_result_mux_id_i[2] -type PI PI
add mapped point alu_result_mux_id_i[1] alu_result_mux_id_i[1] -type PI PI
add mapped point alu_result_mux_id_i[0] alu_result_mux_id_i[0] -type PI PI
add mapped point rd_addr_id_i[4] rd_addr_id_i[4] -type PI PI
add mapped point rd_addr_id_i[3] rd_addr_id_i[3] -type PI PI
add mapped point rd_addr_id_i[2] rd_addr_id_i[2] -type PI PI
add mapped point rd_addr_id_i[1] rd_addr_id_i[1] -type PI PI
add mapped point rd_addr_id_i[0] rd_addr_id_i[0] -type PI PI
add mapped point rd_dst_bank_id_i rd_dst_bank_id_i -type PI PI
add mapped point mem_wen_id_i mem_wen_id_i -type PI PI
add mapped point mem_data_type_id_i[1] mem_data_type_id_i[1] -type PI PI
add mapped point mem_data_type_id_i[0] mem_data_type_id_i[0] -type PI PI
add mapped point mem_sign_extend_id_i mem_sign_extend_id_i -type PI PI
add mapped point reg_alu_wen_id_i reg_alu_wen_id_i -type PI PI
add mapped point reg_mem_wen_id_i reg_mem_wen_id_i -type PI PI
add mapped point pc_id_i[31] pc_id_i[31] -type PI PI
add mapped point pc_id_i[30] pc_id_i[30] -type PI PI
add mapped point pc_id_i[29] pc_id_i[29] -type PI PI
add mapped point pc_id_i[28] pc_id_i[28] -type PI PI
add mapped point pc_id_i[27] pc_id_i[27] -type PI PI
add mapped point pc_id_i[26] pc_id_i[26] -type PI PI
add mapped point pc_id_i[25] pc_id_i[25] -type PI PI
add mapped point pc_id_i[24] pc_id_i[24] -type PI PI
add mapped point pc_id_i[23] pc_id_i[23] -type PI PI
add mapped point pc_id_i[22] pc_id_i[22] -type PI PI
add mapped point pc_id_i[21] pc_id_i[21] -type PI PI
add mapped point pc_id_i[20] pc_id_i[20] -type PI PI
add mapped point pc_id_i[19] pc_id_i[19] -type PI PI
add mapped point pc_id_i[18] pc_id_i[18] -type PI PI
add mapped point pc_id_i[17] pc_id_i[17] -type PI PI
add mapped point pc_id_i[16] pc_id_i[16] -type PI PI
add mapped point pc_id_i[15] pc_id_i[15] -type PI PI
add mapped point pc_id_i[14] pc_id_i[14] -type PI PI
add mapped point pc_id_i[13] pc_id_i[13] -type PI PI
add mapped point pc_id_i[12] pc_id_i[12] -type PI PI
add mapped point pc_id_i[11] pc_id_i[11] -type PI PI
add mapped point pc_id_i[10] pc_id_i[10] -type PI PI
add mapped point pc_id_i[9] pc_id_i[9] -type PI PI
add mapped point pc_id_i[8] pc_id_i[8] -type PI PI
add mapped point pc_id_i[7] pc_id_i[7] -type PI PI
add mapped point pc_id_i[6] pc_id_i[6] -type PI PI
add mapped point pc_id_i[5] pc_id_i[5] -type PI PI
add mapped point pc_id_i[4] pc_id_i[4] -type PI PI
add mapped point pc_id_i[3] pc_id_i[3] -type PI PI
add mapped point pc_id_i[2] pc_id_i[2] -type PI PI
add mapped point pc_id_i[1] pc_id_i[1] -type PI PI
add mapped point pc_id_i[0] pc_id_i[0] -type PI PI
add mapped point pc_source_id_i[1] pc_source_id_i[1] -type PI PI
add mapped point pc_source_id_i[0] pc_source_id_i[0] -type PI PI
add mapped point is_branch_id_i is_branch_id_i -type PI PI
add mapped point alu_operand_1_id_i[31] alu_operand_1_id_i[31] -type PI PI
add mapped point alu_operand_1_id_i[30] alu_operand_1_id_i[30] -type PI PI
add mapped point alu_operand_1_id_i[29] alu_operand_1_id_i[29] -type PI PI
add mapped point alu_operand_1_id_i[28] alu_operand_1_id_i[28] -type PI PI
add mapped point alu_operand_1_id_i[27] alu_operand_1_id_i[27] -type PI PI
add mapped point alu_operand_1_id_i[26] alu_operand_1_id_i[26] -type PI PI
add mapped point alu_operand_1_id_i[25] alu_operand_1_id_i[25] -type PI PI
add mapped point alu_operand_1_id_i[24] alu_operand_1_id_i[24] -type PI PI
add mapped point alu_operand_1_id_i[23] alu_operand_1_id_i[23] -type PI PI
add mapped point alu_operand_1_id_i[22] alu_operand_1_id_i[22] -type PI PI
add mapped point alu_operand_1_id_i[21] alu_operand_1_id_i[21] -type PI PI
add mapped point alu_operand_1_id_i[20] alu_operand_1_id_i[20] -type PI PI
add mapped point alu_operand_1_id_i[19] alu_operand_1_id_i[19] -type PI PI
add mapped point alu_operand_1_id_i[18] alu_operand_1_id_i[18] -type PI PI
add mapped point alu_operand_1_id_i[17] alu_operand_1_id_i[17] -type PI PI
add mapped point alu_operand_1_id_i[16] alu_operand_1_id_i[16] -type PI PI
add mapped point alu_operand_1_id_i[15] alu_operand_1_id_i[15] -type PI PI
add mapped point alu_operand_1_id_i[14] alu_operand_1_id_i[14] -type PI PI
add mapped point alu_operand_1_id_i[13] alu_operand_1_id_i[13] -type PI PI
add mapped point alu_operand_1_id_i[12] alu_operand_1_id_i[12] -type PI PI
add mapped point alu_operand_1_id_i[11] alu_operand_1_id_i[11] -type PI PI
add mapped point alu_operand_1_id_i[10] alu_operand_1_id_i[10] -type PI PI
add mapped point alu_operand_1_id_i[9] alu_operand_1_id_i[9] -type PI PI
add mapped point alu_operand_1_id_i[8] alu_operand_1_id_i[8] -type PI PI
add mapped point alu_operand_1_id_i[7] alu_operand_1_id_i[7] -type PI PI
add mapped point alu_operand_1_id_i[6] alu_operand_1_id_i[6] -type PI PI
add mapped point alu_operand_1_id_i[5] alu_operand_1_id_i[5] -type PI PI
add mapped point alu_operand_1_id_i[4] alu_operand_1_id_i[4] -type PI PI
add mapped point alu_operand_1_id_i[3] alu_operand_1_id_i[3] -type PI PI
add mapped point alu_operand_1_id_i[2] alu_operand_1_id_i[2] -type PI PI
add mapped point alu_operand_1_id_i[1] alu_operand_1_id_i[1] -type PI PI
add mapped point alu_operand_1_id_i[0] alu_operand_1_id_i[0] -type PI PI
add mapped point alu_operand_2_id_i[31] alu_operand_2_id_i[31] -type PI PI
add mapped point alu_operand_2_id_i[30] alu_operand_2_id_i[30] -type PI PI
add mapped point alu_operand_2_id_i[29] alu_operand_2_id_i[29] -type PI PI
add mapped point alu_operand_2_id_i[28] alu_operand_2_id_i[28] -type PI PI
add mapped point alu_operand_2_id_i[27] alu_operand_2_id_i[27] -type PI PI
add mapped point alu_operand_2_id_i[26] alu_operand_2_id_i[26] -type PI PI
add mapped point alu_operand_2_id_i[25] alu_operand_2_id_i[25] -type PI PI
add mapped point alu_operand_2_id_i[24] alu_operand_2_id_i[24] -type PI PI
add mapped point alu_operand_2_id_i[23] alu_operand_2_id_i[23] -type PI PI
add mapped point alu_operand_2_id_i[22] alu_operand_2_id_i[22] -type PI PI
add mapped point alu_operand_2_id_i[21] alu_operand_2_id_i[21] -type PI PI
add mapped point alu_operand_2_id_i[20] alu_operand_2_id_i[20] -type PI PI
add mapped point alu_operand_2_id_i[19] alu_operand_2_id_i[19] -type PI PI
add mapped point alu_operand_2_id_i[18] alu_operand_2_id_i[18] -type PI PI
add mapped point alu_operand_2_id_i[17] alu_operand_2_id_i[17] -type PI PI
add mapped point alu_operand_2_id_i[16] alu_operand_2_id_i[16] -type PI PI
add mapped point alu_operand_2_id_i[15] alu_operand_2_id_i[15] -type PI PI
add mapped point alu_operand_2_id_i[14] alu_operand_2_id_i[14] -type PI PI
add mapped point alu_operand_2_id_i[13] alu_operand_2_id_i[13] -type PI PI
add mapped point alu_operand_2_id_i[12] alu_operand_2_id_i[12] -type PI PI
add mapped point alu_operand_2_id_i[11] alu_operand_2_id_i[11] -type PI PI
add mapped point alu_operand_2_id_i[10] alu_operand_2_id_i[10] -type PI PI
add mapped point alu_operand_2_id_i[9] alu_operand_2_id_i[9] -type PI PI
add mapped point alu_operand_2_id_i[8] alu_operand_2_id_i[8] -type PI PI
add mapped point alu_operand_2_id_i[7] alu_operand_2_id_i[7] -type PI PI
add mapped point alu_operand_2_id_i[6] alu_operand_2_id_i[6] -type PI PI
add mapped point alu_operand_2_id_i[5] alu_operand_2_id_i[5] -type PI PI
add mapped point alu_operand_2_id_i[4] alu_operand_2_id_i[4] -type PI PI
add mapped point alu_operand_2_id_i[3] alu_operand_2_id_i[3] -type PI PI
add mapped point alu_operand_2_id_i[2] alu_operand_2_id_i[2] -type PI PI
add mapped point alu_operand_2_id_i[1] alu_operand_2_id_i[1] -type PI PI
add mapped point alu_operand_2_id_i[0] alu_operand_2_id_i[0] -type PI PI
add mapped point alu_operand_3_id_i[31] alu_operand_3_id_i[31] -type PI PI
add mapped point alu_operand_3_id_i[30] alu_operand_3_id_i[30] -type PI PI
add mapped point alu_operand_3_id_i[29] alu_operand_3_id_i[29] -type PI PI
add mapped point alu_operand_3_id_i[28] alu_operand_3_id_i[28] -type PI PI
add mapped point alu_operand_3_id_i[27] alu_operand_3_id_i[27] -type PI PI
add mapped point alu_operand_3_id_i[26] alu_operand_3_id_i[26] -type PI PI
add mapped point alu_operand_3_id_i[25] alu_operand_3_id_i[25] -type PI PI
add mapped point alu_operand_3_id_i[24] alu_operand_3_id_i[24] -type PI PI
add mapped point alu_operand_3_id_i[23] alu_operand_3_id_i[23] -type PI PI
add mapped point alu_operand_3_id_i[22] alu_operand_3_id_i[22] -type PI PI
add mapped point alu_operand_3_id_i[21] alu_operand_3_id_i[21] -type PI PI
add mapped point alu_operand_3_id_i[20] alu_operand_3_id_i[20] -type PI PI
add mapped point alu_operand_3_id_i[19] alu_operand_3_id_i[19] -type PI PI
add mapped point alu_operand_3_id_i[18] alu_operand_3_id_i[18] -type PI PI
add mapped point alu_operand_3_id_i[17] alu_operand_3_id_i[17] -type PI PI
add mapped point alu_operand_3_id_i[16] alu_operand_3_id_i[16] -type PI PI
add mapped point alu_operand_3_id_i[15] alu_operand_3_id_i[15] -type PI PI
add mapped point alu_operand_3_id_i[14] alu_operand_3_id_i[14] -type PI PI
add mapped point alu_operand_3_id_i[13] alu_operand_3_id_i[13] -type PI PI
add mapped point alu_operand_3_id_i[12] alu_operand_3_id_i[12] -type PI PI
add mapped point alu_operand_3_id_i[11] alu_operand_3_id_i[11] -type PI PI
add mapped point alu_operand_3_id_i[10] alu_operand_3_id_i[10] -type PI PI
add mapped point alu_operand_3_id_i[9] alu_operand_3_id_i[9] -type PI PI
add mapped point alu_operand_3_id_i[8] alu_operand_3_id_i[8] -type PI PI
add mapped point alu_operand_3_id_i[7] alu_operand_3_id_i[7] -type PI PI
add mapped point alu_operand_3_id_i[6] alu_operand_3_id_i[6] -type PI PI
add mapped point alu_operand_3_id_i[5] alu_operand_3_id_i[5] -type PI PI
add mapped point alu_operand_3_id_i[4] alu_operand_3_id_i[4] -type PI PI
add mapped point alu_operand_3_id_i[3] alu_operand_3_id_i[3] -type PI PI
add mapped point alu_operand_3_id_i[2] alu_operand_3_id_i[2] -type PI PI
add mapped point alu_operand_3_id_i[1] alu_operand_3_id_i[1] -type PI PI
add mapped point alu_operand_3_id_i[0] alu_operand_3_id_i[0] -type PI PI
add mapped point mem_wdata_id_i[31] mem_wdata_id_i[31] -type PI PI
add mapped point mem_wdata_id_i[30] mem_wdata_id_i[30] -type PI PI
add mapped point mem_wdata_id_i[29] mem_wdata_id_i[29] -type PI PI
add mapped point mem_wdata_id_i[28] mem_wdata_id_i[28] -type PI PI
add mapped point mem_wdata_id_i[27] mem_wdata_id_i[27] -type PI PI
add mapped point mem_wdata_id_i[26] mem_wdata_id_i[26] -type PI PI
add mapped point mem_wdata_id_i[25] mem_wdata_id_i[25] -type PI PI
add mapped point mem_wdata_id_i[24] mem_wdata_id_i[24] -type PI PI
add mapped point mem_wdata_id_i[23] mem_wdata_id_i[23] -type PI PI
add mapped point mem_wdata_id_i[22] mem_wdata_id_i[22] -type PI PI
add mapped point mem_wdata_id_i[21] mem_wdata_id_i[21] -type PI PI
add mapped point mem_wdata_id_i[20] mem_wdata_id_i[20] -type PI PI
add mapped point mem_wdata_id_i[19] mem_wdata_id_i[19] -type PI PI
add mapped point mem_wdata_id_i[18] mem_wdata_id_i[18] -type PI PI
add mapped point mem_wdata_id_i[17] mem_wdata_id_i[17] -type PI PI
add mapped point mem_wdata_id_i[16] mem_wdata_id_i[16] -type PI PI
add mapped point mem_wdata_id_i[15] mem_wdata_id_i[15] -type PI PI
add mapped point mem_wdata_id_i[14] mem_wdata_id_i[14] -type PI PI
add mapped point mem_wdata_id_i[13] mem_wdata_id_i[13] -type PI PI
add mapped point mem_wdata_id_i[12] mem_wdata_id_i[12] -type PI PI
add mapped point mem_wdata_id_i[11] mem_wdata_id_i[11] -type PI PI
add mapped point mem_wdata_id_i[10] mem_wdata_id_i[10] -type PI PI
add mapped point mem_wdata_id_i[9] mem_wdata_id_i[9] -type PI PI
add mapped point mem_wdata_id_i[8] mem_wdata_id_i[8] -type PI PI
add mapped point mem_wdata_id_i[7] mem_wdata_id_i[7] -type PI PI
add mapped point mem_wdata_id_i[6] mem_wdata_id_i[6] -type PI PI
add mapped point mem_wdata_id_i[5] mem_wdata_id_i[5] -type PI PI
add mapped point mem_wdata_id_i[4] mem_wdata_id_i[4] -type PI PI
add mapped point mem_wdata_id_i[3] mem_wdata_id_i[3] -type PI PI
add mapped point mem_wdata_id_i[2] mem_wdata_id_i[2] -type PI PI
add mapped point mem_wdata_id_i[1] mem_wdata_id_i[1] -type PI PI
add mapped point mem_wdata_id_i[0] mem_wdata_id_i[0] -type PI PI
add mapped point branch_target_id_i[31] branch_target_id_i[31] -type PI PI
add mapped point branch_target_id_i[30] branch_target_id_i[30] -type PI PI
add mapped point branch_target_id_i[29] branch_target_id_i[29] -type PI PI
add mapped point branch_target_id_i[28] branch_target_id_i[28] -type PI PI
add mapped point branch_target_id_i[27] branch_target_id_i[27] -type PI PI
add mapped point branch_target_id_i[26] branch_target_id_i[26] -type PI PI
add mapped point branch_target_id_i[25] branch_target_id_i[25] -type PI PI
add mapped point branch_target_id_i[24] branch_target_id_i[24] -type PI PI
add mapped point branch_target_id_i[23] branch_target_id_i[23] -type PI PI
add mapped point branch_target_id_i[22] branch_target_id_i[22] -type PI PI
add mapped point branch_target_id_i[21] branch_target_id_i[21] -type PI PI
add mapped point branch_target_id_i[20] branch_target_id_i[20] -type PI PI
add mapped point branch_target_id_i[19] branch_target_id_i[19] -type PI PI
add mapped point branch_target_id_i[18] branch_target_id_i[18] -type PI PI
add mapped point branch_target_id_i[17] branch_target_id_i[17] -type PI PI
add mapped point branch_target_id_i[16] branch_target_id_i[16] -type PI PI
add mapped point branch_target_id_i[15] branch_target_id_i[15] -type PI PI
add mapped point branch_target_id_i[14] branch_target_id_i[14] -type PI PI
add mapped point branch_target_id_i[13] branch_target_id_i[13] -type PI PI
add mapped point branch_target_id_i[12] branch_target_id_i[12] -type PI PI
add mapped point branch_target_id_i[11] branch_target_id_i[11] -type PI PI
add mapped point branch_target_id_i[10] branch_target_id_i[10] -type PI PI
add mapped point branch_target_id_i[9] branch_target_id_i[9] -type PI PI
add mapped point branch_target_id_i[8] branch_target_id_i[8] -type PI PI
add mapped point branch_target_id_i[7] branch_target_id_i[7] -type PI PI
add mapped point branch_target_id_i[6] branch_target_id_i[6] -type PI PI
add mapped point branch_target_id_i[5] branch_target_id_i[5] -type PI PI
add mapped point branch_target_id_i[4] branch_target_id_i[4] -type PI PI
add mapped point branch_target_id_i[3] branch_target_id_i[3] -type PI PI
add mapped point branch_target_id_i[2] branch_target_id_i[2] -type PI PI
add mapped point branch_target_id_i[1] branch_target_id_i[1] -type PI PI
add mapped point branch_target_id_i[0] branch_target_id_i[0] -type PI PI
add mapped point valid_id_i valid_id_i -type PI PI
add mapped point csr_access_id_i csr_access_id_i -type PI PI
add mapped point csr_op_id_i[1] csr_op_id_i[1] -type PI PI
add mapped point csr_op_id_i[0] csr_op_id_i[0] -type PI PI
add mapped point csr_rdata_ex_i[31] csr_rdata_ex_i[31] -type PI PI
add mapped point csr_rdata_ex_i[30] csr_rdata_ex_i[30] -type PI PI
add mapped point csr_rdata_ex_i[29] csr_rdata_ex_i[29] -type PI PI
add mapped point csr_rdata_ex_i[28] csr_rdata_ex_i[28] -type PI PI
add mapped point csr_rdata_ex_i[27] csr_rdata_ex_i[27] -type PI PI
add mapped point csr_rdata_ex_i[26] csr_rdata_ex_i[26] -type PI PI
add mapped point csr_rdata_ex_i[25] csr_rdata_ex_i[25] -type PI PI
add mapped point csr_rdata_ex_i[24] csr_rdata_ex_i[24] -type PI PI
add mapped point csr_rdata_ex_i[23] csr_rdata_ex_i[23] -type PI PI
add mapped point csr_rdata_ex_i[22] csr_rdata_ex_i[22] -type PI PI
add mapped point csr_rdata_ex_i[21] csr_rdata_ex_i[21] -type PI PI
add mapped point csr_rdata_ex_i[20] csr_rdata_ex_i[20] -type PI PI
add mapped point csr_rdata_ex_i[19] csr_rdata_ex_i[19] -type PI PI
add mapped point csr_rdata_ex_i[18] csr_rdata_ex_i[18] -type PI PI
add mapped point csr_rdata_ex_i[17] csr_rdata_ex_i[17] -type PI PI
add mapped point csr_rdata_ex_i[16] csr_rdata_ex_i[16] -type PI PI
add mapped point csr_rdata_ex_i[15] csr_rdata_ex_i[15] -type PI PI
add mapped point csr_rdata_ex_i[14] csr_rdata_ex_i[14] -type PI PI
add mapped point csr_rdata_ex_i[13] csr_rdata_ex_i[13] -type PI PI
add mapped point csr_rdata_ex_i[12] csr_rdata_ex_i[12] -type PI PI
add mapped point csr_rdata_ex_i[11] csr_rdata_ex_i[11] -type PI PI
add mapped point csr_rdata_ex_i[10] csr_rdata_ex_i[10] -type PI PI
add mapped point csr_rdata_ex_i[9] csr_rdata_ex_i[9] -type PI PI
add mapped point csr_rdata_ex_i[8] csr_rdata_ex_i[8] -type PI PI
add mapped point csr_rdata_ex_i[7] csr_rdata_ex_i[7] -type PI PI
add mapped point csr_rdata_ex_i[6] csr_rdata_ex_i[6] -type PI PI
add mapped point csr_rdata_ex_i[5] csr_rdata_ex_i[5] -type PI PI
add mapped point csr_rdata_ex_i[4] csr_rdata_ex_i[4] -type PI PI
add mapped point csr_rdata_ex_i[3] csr_rdata_ex_i[3] -type PI PI
add mapped point csr_rdata_ex_i[2] csr_rdata_ex_i[2] -type PI PI
add mapped point csr_rdata_ex_i[1] csr_rdata_ex_i[1] -type PI PI
add mapped point csr_rdata_ex_i[0] csr_rdata_ex_i[0] -type PI PI
add mapped point stall_ex_i stall_ex_i -type PI PI
add mapped point flush_ex_i flush_ex_i -type PI PI
add mapped point m_operation_id_i[2] m_operation_id_i[2] -type PI PI
add mapped point m_operation_id_i[1] m_operation_id_i[1] -type PI PI
add mapped point m_operation_id_i[0] m_operation_id_i[0] -type PI PI
add mapped point div_req_id_i div_req_id_i -type PI PI
add mapped point mul_req_id_i mul_req_id_i -type PI PI
add mapped point fpu_rnd_mode_id_i[2] fpu_rnd_mode_id_i[2] -type PI PI
add mapped point fpu_rnd_mode_id_i[1] fpu_rnd_mode_id_i[1] -type PI PI
add mapped point fpu_rnd_mode_id_i[0] fpu_rnd_mode_id_i[0] -type PI PI
add mapped point fpu_op_id_i[3] fpu_op_id_i[3] -type PI PI
add mapped point fpu_op_id_i[2] fpu_op_id_i[2] -type PI PI
add mapped point fpu_op_id_i[1] fpu_op_id_i[1] -type PI PI
add mapped point fpu_op_id_i[0] fpu_op_id_i[0] -type PI PI
add mapped point fpu_frm_i[2] fpu_frm_i[2] -type PI PI
add mapped point fpu_frm_i[1] fpu_frm_i[1] -type PI PI
add mapped point fpu_frm_i[0] fpu_frm_i[0] -type PI PI
add mapped point fpu_op_mod_id_i fpu_op_mod_id_i -type PI PI
add mapped point fpu_req_id_i fpu_req_id_i -type PI PI

//output ports
add mapped point pc_source_ex_o[1] pc_source_ex_o[1] -type PO PO
add mapped point pc_source_ex_o[0] pc_source_ex_o[0] -type PO PO
add mapped point branch_target_ex_o[31] branch_target_ex_o[31] -type PO PO
add mapped point branch_target_ex_o[30] branch_target_ex_o[30] -type PO PO
add mapped point branch_target_ex_o[29] branch_target_ex_o[29] -type PO PO
add mapped point branch_target_ex_o[28] branch_target_ex_o[28] -type PO PO
add mapped point branch_target_ex_o[27] branch_target_ex_o[27] -type PO PO
add mapped point branch_target_ex_o[26] branch_target_ex_o[26] -type PO PO
add mapped point branch_target_ex_o[25] branch_target_ex_o[25] -type PO PO
add mapped point branch_target_ex_o[24] branch_target_ex_o[24] -type PO PO
add mapped point branch_target_ex_o[23] branch_target_ex_o[23] -type PO PO
add mapped point branch_target_ex_o[22] branch_target_ex_o[22] -type PO PO
add mapped point branch_target_ex_o[21] branch_target_ex_o[21] -type PO PO
add mapped point branch_target_ex_o[20] branch_target_ex_o[20] -type PO PO
add mapped point branch_target_ex_o[19] branch_target_ex_o[19] -type PO PO
add mapped point branch_target_ex_o[18] branch_target_ex_o[18] -type PO PO
add mapped point branch_target_ex_o[17] branch_target_ex_o[17] -type PO PO
add mapped point branch_target_ex_o[16] branch_target_ex_o[16] -type PO PO
add mapped point branch_target_ex_o[15] branch_target_ex_o[15] -type PO PO
add mapped point branch_target_ex_o[14] branch_target_ex_o[14] -type PO PO
add mapped point branch_target_ex_o[13] branch_target_ex_o[13] -type PO PO
add mapped point branch_target_ex_o[12] branch_target_ex_o[12] -type PO PO
add mapped point branch_target_ex_o[11] branch_target_ex_o[11] -type PO PO
add mapped point branch_target_ex_o[10] branch_target_ex_o[10] -type PO PO
add mapped point branch_target_ex_o[9] branch_target_ex_o[9] -type PO PO
add mapped point branch_target_ex_o[8] branch_target_ex_o[8] -type PO PO
add mapped point branch_target_ex_o[7] branch_target_ex_o[7] -type PO PO
add mapped point branch_target_ex_o[6] branch_target_ex_o[6] -type PO PO
add mapped point branch_target_ex_o[5] branch_target_ex_o[5] -type PO PO
add mapped point branch_target_ex_o[4] branch_target_ex_o[4] -type PO PO
add mapped point branch_target_ex_o[3] branch_target_ex_o[3] -type PO PO
add mapped point branch_target_ex_o[2] branch_target_ex_o[2] -type PO PO
add mapped point branch_target_ex_o[1] branch_target_ex_o[1] -type PO PO
add mapped point branch_target_ex_o[0] branch_target_ex_o[0] -type PO PO
add mapped point branch_decision_ex_o branch_decision_ex_o -type PO PO
add mapped point trap_ex_o trap_ex_o -type PO PO
add mapped point rd_addr_ex_o[4] rd_addr_ex_o[4] -type PO PO
add mapped point rd_addr_ex_o[3] rd_addr_ex_o[3] -type PO PO
add mapped point rd_addr_ex_o[2] rd_addr_ex_o[2] -type PO PO
add mapped point rd_addr_ex_o[1] rd_addr_ex_o[1] -type PO PO
add mapped point rd_addr_ex_o[0] rd_addr_ex_o[0] -type PO PO
add mapped point rd_dst_bank_ex_o rd_dst_bank_ex_o -type PO PO
add mapped point alu_result_ex_o[31] alu_result_ex_o[31] -type PO PO
add mapped point alu_result_ex_o[30] alu_result_ex_o[30] -type PO PO
add mapped point alu_result_ex_o[29] alu_result_ex_o[29] -type PO PO
add mapped point alu_result_ex_o[28] alu_result_ex_o[28] -type PO PO
add mapped point alu_result_ex_o[27] alu_result_ex_o[27] -type PO PO
add mapped point alu_result_ex_o[26] alu_result_ex_o[26] -type PO PO
add mapped point alu_result_ex_o[25] alu_result_ex_o[25] -type PO PO
add mapped point alu_result_ex_o[24] alu_result_ex_o[24] -type PO PO
add mapped point alu_result_ex_o[23] alu_result_ex_o[23] -type PO PO
add mapped point alu_result_ex_o[22] alu_result_ex_o[22] -type PO PO
add mapped point alu_result_ex_o[21] alu_result_ex_o[21] -type PO PO
add mapped point alu_result_ex_o[20] alu_result_ex_o[20] -type PO PO
add mapped point alu_result_ex_o[19] alu_result_ex_o[19] -type PO PO
add mapped point alu_result_ex_o[18] alu_result_ex_o[18] -type PO PO
add mapped point alu_result_ex_o[17] alu_result_ex_o[17] -type PO PO
add mapped point alu_result_ex_o[16] alu_result_ex_o[16] -type PO PO
add mapped point alu_result_ex_o[15] alu_result_ex_o[15] -type PO PO
add mapped point alu_result_ex_o[14] alu_result_ex_o[14] -type PO PO
add mapped point alu_result_ex_o[13] alu_result_ex_o[13] -type PO PO
add mapped point alu_result_ex_o[12] alu_result_ex_o[12] -type PO PO
add mapped point alu_result_ex_o[11] alu_result_ex_o[11] -type PO PO
add mapped point alu_result_ex_o[10] alu_result_ex_o[10] -type PO PO
add mapped point alu_result_ex_o[9] alu_result_ex_o[9] -type PO PO
add mapped point alu_result_ex_o[8] alu_result_ex_o[8] -type PO PO
add mapped point alu_result_ex_o[7] alu_result_ex_o[7] -type PO PO
add mapped point alu_result_ex_o[6] alu_result_ex_o[6] -type PO PO
add mapped point alu_result_ex_o[5] alu_result_ex_o[5] -type PO PO
add mapped point alu_result_ex_o[4] alu_result_ex_o[4] -type PO PO
add mapped point alu_result_ex_o[3] alu_result_ex_o[3] -type PO PO
add mapped point alu_result_ex_o[2] alu_result_ex_o[2] -type PO PO
add mapped point alu_result_ex_o[1] alu_result_ex_o[1] -type PO PO
add mapped point alu_result_ex_o[0] alu_result_ex_o[0] -type PO PO
add mapped point mem_wen_ex_o mem_wen_ex_o -type PO PO
add mapped point mem_data_type_ex_o[1] mem_data_type_ex_o[1] -type PO PO
add mapped point mem_data_type_ex_o[0] mem_data_type_ex_o[0] -type PO PO
add mapped point mem_sign_extend_ex_o mem_sign_extend_ex_o -type PO PO
add mapped point mem_wdata_ex_o[31] mem_wdata_ex_o[31] -type PO PO
add mapped point mem_wdata_ex_o[30] mem_wdata_ex_o[30] -type PO PO
add mapped point mem_wdata_ex_o[29] mem_wdata_ex_o[29] -type PO PO
add mapped point mem_wdata_ex_o[28] mem_wdata_ex_o[28] -type PO PO
add mapped point mem_wdata_ex_o[27] mem_wdata_ex_o[27] -type PO PO
add mapped point mem_wdata_ex_o[26] mem_wdata_ex_o[26] -type PO PO
add mapped point mem_wdata_ex_o[25] mem_wdata_ex_o[25] -type PO PO
add mapped point mem_wdata_ex_o[24] mem_wdata_ex_o[24] -type PO PO
add mapped point mem_wdata_ex_o[23] mem_wdata_ex_o[23] -type PO PO
add mapped point mem_wdata_ex_o[22] mem_wdata_ex_o[22] -type PO PO
add mapped point mem_wdata_ex_o[21] mem_wdata_ex_o[21] -type PO PO
add mapped point mem_wdata_ex_o[20] mem_wdata_ex_o[20] -type PO PO
add mapped point mem_wdata_ex_o[19] mem_wdata_ex_o[19] -type PO PO
add mapped point mem_wdata_ex_o[18] mem_wdata_ex_o[18] -type PO PO
add mapped point mem_wdata_ex_o[17] mem_wdata_ex_o[17] -type PO PO
add mapped point mem_wdata_ex_o[16] mem_wdata_ex_o[16] -type PO PO
add mapped point mem_wdata_ex_o[15] mem_wdata_ex_o[15] -type PO PO
add mapped point mem_wdata_ex_o[14] mem_wdata_ex_o[14] -type PO PO
add mapped point mem_wdata_ex_o[13] mem_wdata_ex_o[13] -type PO PO
add mapped point mem_wdata_ex_o[12] mem_wdata_ex_o[12] -type PO PO
add mapped point mem_wdata_ex_o[11] mem_wdata_ex_o[11] -type PO PO
add mapped point mem_wdata_ex_o[10] mem_wdata_ex_o[10] -type PO PO
add mapped point mem_wdata_ex_o[9] mem_wdata_ex_o[9] -type PO PO
add mapped point mem_wdata_ex_o[8] mem_wdata_ex_o[8] -type PO PO
add mapped point mem_wdata_ex_o[7] mem_wdata_ex_o[7] -type PO PO
add mapped point mem_wdata_ex_o[6] mem_wdata_ex_o[6] -type PO PO
add mapped point mem_wdata_ex_o[5] mem_wdata_ex_o[5] -type PO PO
add mapped point mem_wdata_ex_o[4] mem_wdata_ex_o[4] -type PO PO
add mapped point mem_wdata_ex_o[3] mem_wdata_ex_o[3] -type PO PO
add mapped point mem_wdata_ex_o[2] mem_wdata_ex_o[2] -type PO PO
add mapped point mem_wdata_ex_o[1] mem_wdata_ex_o[1] -type PO PO
add mapped point mem_wdata_ex_o[0] mem_wdata_ex_o[0] -type PO PO
add mapped point reg_alu_wen_ex_o reg_alu_wen_ex_o -type PO PO
add mapped point reg_mem_wen_ex_o reg_mem_wen_ex_o -type PO PO
add mapped point valid_ex_o valid_ex_o -type PO PO
add mapped point pc_ex_o[31] pc_ex_o[31] -type PO PO
add mapped point pc_ex_o[30] pc_ex_o[30] -type PO PO
add mapped point pc_ex_o[29] pc_ex_o[29] -type PO PO
add mapped point pc_ex_o[28] pc_ex_o[28] -type PO PO
add mapped point pc_ex_o[27] pc_ex_o[27] -type PO PO
add mapped point pc_ex_o[26] pc_ex_o[26] -type PO PO
add mapped point pc_ex_o[25] pc_ex_o[25] -type PO PO
add mapped point pc_ex_o[24] pc_ex_o[24] -type PO PO
add mapped point pc_ex_o[23] pc_ex_o[23] -type PO PO
add mapped point pc_ex_o[22] pc_ex_o[22] -type PO PO
add mapped point pc_ex_o[21] pc_ex_o[21] -type PO PO
add mapped point pc_ex_o[20] pc_ex_o[20] -type PO PO
add mapped point pc_ex_o[19] pc_ex_o[19] -type PO PO
add mapped point pc_ex_o[18] pc_ex_o[18] -type PO PO
add mapped point pc_ex_o[17] pc_ex_o[17] -type PO PO
add mapped point pc_ex_o[16] pc_ex_o[16] -type PO PO
add mapped point pc_ex_o[15] pc_ex_o[15] -type PO PO
add mapped point pc_ex_o[14] pc_ex_o[14] -type PO PO
add mapped point pc_ex_o[13] pc_ex_o[13] -type PO PO
add mapped point pc_ex_o[12] pc_ex_o[12] -type PO PO
add mapped point pc_ex_o[11] pc_ex_o[11] -type PO PO
add mapped point pc_ex_o[10] pc_ex_o[10] -type PO PO
add mapped point pc_ex_o[9] pc_ex_o[9] -type PO PO
add mapped point pc_ex_o[8] pc_ex_o[8] -type PO PO
add mapped point pc_ex_o[7] pc_ex_o[7] -type PO PO
add mapped point pc_ex_o[6] pc_ex_o[6] -type PO PO
add mapped point pc_ex_o[5] pc_ex_o[5] -type PO PO
add mapped point pc_ex_o[4] pc_ex_o[4] -type PO PO
add mapped point pc_ex_o[3] pc_ex_o[3] -type PO PO
add mapped point pc_ex_o[2] pc_ex_o[2] -type PO PO
add mapped point pc_ex_o[1] pc_ex_o[1] -type PO PO
add mapped point pc_ex_o[0] pc_ex_o[0] -type PO PO
add mapped point csr_addr_ex_o[11] csr_addr_ex_o[11] -type PO PO
add mapped point csr_addr_ex_o[10] csr_addr_ex_o[10] -type PO PO
add mapped point csr_addr_ex_o[9] csr_addr_ex_o[9] -type PO PO
add mapped point csr_addr_ex_o[8] csr_addr_ex_o[8] -type PO PO
add mapped point csr_addr_ex_o[7] csr_addr_ex_o[7] -type PO PO
add mapped point csr_addr_ex_o[6] csr_addr_ex_o[6] -type PO PO
add mapped point csr_addr_ex_o[5] csr_addr_ex_o[5] -type PO PO
add mapped point csr_addr_ex_o[4] csr_addr_ex_o[4] -type PO PO
add mapped point csr_addr_ex_o[3] csr_addr_ex_o[3] -type PO PO
add mapped point csr_addr_ex_o[2] csr_addr_ex_o[2] -type PO PO
add mapped point csr_addr_ex_o[1] csr_addr_ex_o[1] -type PO PO
add mapped point csr_addr_ex_o[0] csr_addr_ex_o[0] -type PO PO
add mapped point csr_wdata_ex_o[31] csr_wdata_ex_o[31] -type PO PO
add mapped point csr_wdata_ex_o[30] csr_wdata_ex_o[30] -type PO PO
add mapped point csr_wdata_ex_o[29] csr_wdata_ex_o[29] -type PO PO
add mapped point csr_wdata_ex_o[28] csr_wdata_ex_o[28] -type PO PO
add mapped point csr_wdata_ex_o[27] csr_wdata_ex_o[27] -type PO PO
add mapped point csr_wdata_ex_o[26] csr_wdata_ex_o[26] -type PO PO
add mapped point csr_wdata_ex_o[25] csr_wdata_ex_o[25] -type PO PO
add mapped point csr_wdata_ex_o[24] csr_wdata_ex_o[24] -type PO PO
add mapped point csr_wdata_ex_o[23] csr_wdata_ex_o[23] -type PO PO
add mapped point csr_wdata_ex_o[22] csr_wdata_ex_o[22] -type PO PO
add mapped point csr_wdata_ex_o[21] csr_wdata_ex_o[21] -type PO PO
add mapped point csr_wdata_ex_o[20] csr_wdata_ex_o[20] -type PO PO
add mapped point csr_wdata_ex_o[19] csr_wdata_ex_o[19] -type PO PO
add mapped point csr_wdata_ex_o[18] csr_wdata_ex_o[18] -type PO PO
add mapped point csr_wdata_ex_o[17] csr_wdata_ex_o[17] -type PO PO
add mapped point csr_wdata_ex_o[16] csr_wdata_ex_o[16] -type PO PO
add mapped point csr_wdata_ex_o[15] csr_wdata_ex_o[15] -type PO PO
add mapped point csr_wdata_ex_o[14] csr_wdata_ex_o[14] -type PO PO
add mapped point csr_wdata_ex_o[13] csr_wdata_ex_o[13] -type PO PO
add mapped point csr_wdata_ex_o[12] csr_wdata_ex_o[12] -type PO PO
add mapped point csr_wdata_ex_o[11] csr_wdata_ex_o[11] -type PO PO
add mapped point csr_wdata_ex_o[10] csr_wdata_ex_o[10] -type PO PO
add mapped point csr_wdata_ex_o[9] csr_wdata_ex_o[9] -type PO PO
add mapped point csr_wdata_ex_o[8] csr_wdata_ex_o[8] -type PO PO
add mapped point csr_wdata_ex_o[7] csr_wdata_ex_o[7] -type PO PO
add mapped point csr_wdata_ex_o[6] csr_wdata_ex_o[6] -type PO PO
add mapped point csr_wdata_ex_o[5] csr_wdata_ex_o[5] -type PO PO
add mapped point csr_wdata_ex_o[4] csr_wdata_ex_o[4] -type PO PO
add mapped point csr_wdata_ex_o[3] csr_wdata_ex_o[3] -type PO PO
add mapped point csr_wdata_ex_o[2] csr_wdata_ex_o[2] -type PO PO
add mapped point csr_wdata_ex_o[1] csr_wdata_ex_o[1] -type PO PO
add mapped point csr_wdata_ex_o[0] csr_wdata_ex_o[0] -type PO PO
add mapped point csr_op_ex_o[1] csr_op_ex_o[1] -type PO PO
add mapped point csr_op_ex_o[0] csr_op_ex_o[0] -type PO PO
add mapped point csr_access_ex_o csr_access_ex_o -type PO PO
add mapped point csr_fpu_flags_ex_o[4] csr_fpu_flags_ex_o[4] -type PO PO
add mapped point csr_fpu_flags_ex_o[3] csr_fpu_flags_ex_o[3] -type PO PO
add mapped point csr_fpu_flags_ex_o[2] csr_fpu_flags_ex_o[2] -type PO PO
add mapped point csr_fpu_flags_ex_o[1] csr_fpu_flags_ex_o[1] -type PO PO
add mapped point csr_fpu_flags_ex_o[0] csr_fpu_flags_ex_o[0] -type PO PO
add mapped point div_gnt_id_o div_gnt_id_o -type PO PO
add mapped point div_busy_ex_o div_busy_ex_o -type PO PO
add mapped point mul_gnt_id_o mul_gnt_id_o -type PO PO
add mapped point mul_busy_ex_o mul_busy_ex_o -type PO PO
add mapped point fpu_gnt_id_o fpu_gnt_id_o -type PO PO
add mapped point fpu_busy_ex_o fpu_busy_ex_o -type PO PO

//inout ports




//Sequential Pins
add mapped point genblk2.multiplicador/in_ready_o/q genblk2.multiplicador_in_ready_o_reg/Q -type DLAT DLAT
add mapped point genblk2.multiplicador/next_state[0]/q genblk2.multiplicador_next_state_reg[0]/Q -type DLAT DLAT
add mapped point genblk2.multiplicador/next_state[1]/q genblk2.multiplicador_next_state_reg[1]/Q -type DLAT DLAT
add mapped point genblk2.multiplicador/out_valid_o/q genblk2.multiplicador_out_valid_o_reg/Q -type DLAT DLAT
add mapped point alu_operand_1_ex[0]/q alu_operand_1_ex_reg[0]/Q -type DFF DFF
add mapped point alu_operand_1_ex[1]/q alu_operand_1_ex_reg[1]/Q -type DFF DFF
add mapped point alu_operand_1_ex[2]/q alu_operand_1_ex_reg[2]/Q -type DFF DFF
add mapped point alu_operand_1_ex[3]/q alu_operand_1_ex_reg[3]/Q -type DFF DFF
add mapped point alu_operand_1_ex[4]/q alu_operand_1_ex_reg[4]/Q -type DFF DFF
add mapped point alu_operand_1_ex[5]/q alu_operand_1_ex_reg[5]/Q -type DFF DFF
add mapped point alu_operand_1_ex[6]/q alu_operand_1_ex_reg[6]/Q -type DFF DFF
add mapped point alu_operand_1_ex[7]/q alu_operand_1_ex_reg[7]/Q -type DFF DFF
add mapped point alu_operand_1_ex[8]/q alu_operand_1_ex_reg[8]/Q -type DFF DFF
add mapped point alu_operand_1_ex[9]/q alu_operand_1_ex_reg[9]/Q -type DFF DFF
add mapped point alu_operand_1_ex[10]/q alu_operand_1_ex_reg[10]/Q -type DFF DFF
add mapped point alu_operand_1_ex[11]/q alu_operand_1_ex_reg[11]/Q -type DFF DFF
add mapped point alu_operand_1_ex[12]/q alu_operand_1_ex_reg[12]/Q -type DFF DFF
add mapped point alu_operand_1_ex[13]/q alu_operand_1_ex_reg[13]/Q -type DFF DFF
add mapped point alu_operand_1_ex[14]/q alu_operand_1_ex_reg[14]/Q -type DFF DFF
add mapped point alu_operand_1_ex[15]/q alu_operand_1_ex_reg[15]/Q -type DFF DFF
add mapped point alu_operand_1_ex[16]/q alu_operand_1_ex_reg[16]/Q -type DFF DFF
add mapped point alu_operand_1_ex[17]/q alu_operand_1_ex_reg[17]/Q -type DFF DFF
add mapped point alu_operand_1_ex[18]/q alu_operand_1_ex_reg[18]/Q -type DFF DFF
add mapped point alu_operand_1_ex[19]/q alu_operand_1_ex_reg[19]/Q -type DFF DFF
add mapped point alu_operand_1_ex[20]/q alu_operand_1_ex_reg[20]/Q -type DFF DFF
add mapped point alu_operand_1_ex[21]/q alu_operand_1_ex_reg[21]/Q -type DFF DFF
add mapped point alu_operand_1_ex[22]/q alu_operand_1_ex_reg[22]/Q -type DFF DFF
add mapped point alu_operand_1_ex[23]/q alu_operand_1_ex_reg[23]/Q -type DFF DFF
add mapped point alu_operand_1_ex[24]/q alu_operand_1_ex_reg[24]/Q -type DFF DFF
add mapped point alu_operand_1_ex[25]/q alu_operand_1_ex_reg[25]/Q -type DFF DFF
add mapped point alu_operand_1_ex[26]/q alu_operand_1_ex_reg[26]/Q -type DFF DFF
add mapped point alu_operand_1_ex[27]/q alu_operand_1_ex_reg[27]/Q -type DFF DFF
add mapped point alu_operand_1_ex[28]/q alu_operand_1_ex_reg[28]/Q -type DFF DFF
add mapped point alu_operand_1_ex[29]/q alu_operand_1_ex_reg[29]/Q -type DFF DFF
add mapped point alu_operand_1_ex[30]/q alu_operand_1_ex_reg[30]/Q -type DFF DFF
add mapped point alu_operand_1_ex[31]/q alu_operand_1_ex_reg[31]/Q -type DFF DFF
add mapped point alu_operand_2_ex[0]/q alu_operand_2_ex_reg[0]/Q -type DFF DFF
add mapped point alu_operand_2_ex[1]/q alu_operand_2_ex_reg[1]/Q -type DFF DFF
add mapped point alu_operand_2_ex[2]/q alu_operand_2_ex_reg[2]/Q -type DFF DFF
add mapped point alu_operand_2_ex[3]/q alu_operand_2_ex_reg[3]/Q -type DFF DFF
add mapped point alu_operand_2_ex[4]/q alu_operand_2_ex_reg[4]/Q -type DFF DFF
add mapped point alu_operand_2_ex[5]/q alu_operand_2_ex_reg[5]/Q -type DFF DFF
add mapped point alu_operand_2_ex[6]/q alu_operand_2_ex_reg[6]/Q -type DFF DFF
add mapped point alu_operand_2_ex[7]/q alu_operand_2_ex_reg[7]/Q -type DFF DFF
add mapped point alu_operand_2_ex[8]/q alu_operand_2_ex_reg[8]/Q -type DFF DFF
add mapped point alu_operand_2_ex[9]/q alu_operand_2_ex_reg[9]/Q -type DFF DFF
add mapped point alu_operand_2_ex[10]/q alu_operand_2_ex_reg[10]/Q -type DFF DFF
add mapped point alu_operand_2_ex[11]/q alu_operand_2_ex_reg[11]/Q -type DFF DFF
add mapped point alu_operand_2_ex[12]/q alu_operand_2_ex_reg[12]/Q -type DFF DFF
add mapped point alu_operand_2_ex[13]/q alu_operand_2_ex_reg[13]/Q -type DFF DFF
add mapped point alu_operand_2_ex[14]/q alu_operand_2_ex_reg[14]/Q -type DFF DFF
add mapped point alu_operand_2_ex[15]/q alu_operand_2_ex_reg[15]/Q -type DFF DFF
add mapped point alu_operand_2_ex[16]/q alu_operand_2_ex_reg[16]/Q -type DFF DFF
add mapped point alu_operand_2_ex[17]/q alu_operand_2_ex_reg[17]/Q -type DFF DFF
add mapped point alu_operand_2_ex[18]/q alu_operand_2_ex_reg[18]/Q -type DFF DFF
add mapped point alu_operand_2_ex[19]/q alu_operand_2_ex_reg[19]/Q -type DFF DFF
add mapped point alu_operand_2_ex[20]/q alu_operand_2_ex_reg[20]/Q -type DFF DFF
add mapped point alu_operand_2_ex[21]/q alu_operand_2_ex_reg[21]/Q -type DFF DFF
add mapped point alu_operand_2_ex[22]/q alu_operand_2_ex_reg[22]/Q -type DFF DFF
add mapped point alu_operand_2_ex[23]/q alu_operand_2_ex_reg[23]/Q -type DFF DFF
add mapped point alu_operand_2_ex[24]/q alu_operand_2_ex_reg[24]/Q -type DFF DFF
add mapped point alu_operand_2_ex[25]/q alu_operand_2_ex_reg[25]/Q -type DFF DFF
add mapped point alu_operand_2_ex[26]/q alu_operand_2_ex_reg[26]/Q -type DFF DFF
add mapped point alu_operand_2_ex[27]/q alu_operand_2_ex_reg[27]/Q -type DFF DFF
add mapped point alu_operand_2_ex[28]/q alu_operand_2_ex_reg[28]/Q -type DFF DFF
add mapped point alu_operand_2_ex[29]/q alu_operand_2_ex_reg[29]/Q -type DFF DFF
add mapped point alu_operand_2_ex[30]/q alu_operand_2_ex_reg[30]/Q -type DFF DFF
add mapped point alu_operand_2_ex[31]/q alu_operand_2_ex_reg[31]/Q -type DFF DFF
add mapped point alu_operation_ex[0]/q alu_operation_ex_reg[0]/Q -type DFF DFF
add mapped point alu_operation_ex[1]/q alu_operation_ex_reg[1]/Q -type DFF DFF
add mapped point alu_operation_ex[2]/q alu_operation_ex_reg[2]/Q -type DFF DFF
add mapped point alu_operation_ex[3]/q alu_operation_ex_reg[3]/Q -type DFF DFF
add mapped point alu_result_mux_ex[0]/q alu_result_mux_ex_reg[0]/Q -type DFF DFF
add mapped point alu_result_mux_ex[1]/q alu_result_mux_ex_reg[1]/Q -type DFF DFF
add mapped point alu_result_mux_ex[2]/q alu_result_mux_ex_reg[2]/Q -type DFF DFF
add mapped point branch_target_ex_o[0]/q branch_target_ex_o_reg[0]/Q -type DFF DFF
add mapped point branch_target_ex_o[1]/q branch_target_ex_o_reg[1]/Q -type DFF DFF
add mapped point branch_target_ex_o[2]/q branch_target_ex_o_reg[2]/Q -type DFF DFF
add mapped point branch_target_ex_o[3]/q branch_target_ex_o_reg[3]/Q -type DFF DFF
add mapped point branch_target_ex_o[4]/q branch_target_ex_o_reg[4]/Q -type DFF DFF
add mapped point branch_target_ex_o[5]/q branch_target_ex_o_reg[5]/Q -type DFF DFF
add mapped point branch_target_ex_o[6]/q branch_target_ex_o_reg[6]/Q -type DFF DFF
add mapped point branch_target_ex_o[7]/q branch_target_ex_o_reg[7]/Q -type DFF DFF
add mapped point branch_target_ex_o[8]/q branch_target_ex_o_reg[8]/Q -type DFF DFF
add mapped point branch_target_ex_o[9]/q branch_target_ex_o_reg[9]/Q -type DFF DFF
add mapped point branch_target_ex_o[10]/q branch_target_ex_o_reg[10]/Q -type DFF DFF
add mapped point branch_target_ex_o[11]/q branch_target_ex_o_reg[11]/Q -type DFF DFF
add mapped point branch_target_ex_o[12]/q branch_target_ex_o_reg[12]/Q -type DFF DFF
add mapped point branch_target_ex_o[13]/q branch_target_ex_o_reg[13]/Q -type DFF DFF
add mapped point branch_target_ex_o[14]/q branch_target_ex_o_reg[14]/Q -type DFF DFF
add mapped point branch_target_ex_o[15]/q branch_target_ex_o_reg[15]/Q -type DFF DFF
add mapped point branch_target_ex_o[16]/q branch_target_ex_o_reg[16]/Q -type DFF DFF
add mapped point branch_target_ex_o[17]/q branch_target_ex_o_reg[17]/Q -type DFF DFF
add mapped point branch_target_ex_o[18]/q branch_target_ex_o_reg[18]/Q -type DFF DFF
add mapped point branch_target_ex_o[19]/q branch_target_ex_o_reg[19]/Q -type DFF DFF
add mapped point branch_target_ex_o[20]/q branch_target_ex_o_reg[20]/Q -type DFF DFF
add mapped point branch_target_ex_o[21]/q branch_target_ex_o_reg[21]/Q -type DFF DFF
add mapped point branch_target_ex_o[22]/q branch_target_ex_o_reg[22]/Q -type DFF DFF
add mapped point branch_target_ex_o[23]/q branch_target_ex_o_reg[23]/Q -type DFF DFF
add mapped point branch_target_ex_o[24]/q branch_target_ex_o_reg[24]/Q -type DFF DFF
add mapped point branch_target_ex_o[25]/q branch_target_ex_o_reg[25]/Q -type DFF DFF
add mapped point branch_target_ex_o[26]/q branch_target_ex_o_reg[26]/Q -type DFF DFF
add mapped point branch_target_ex_o[27]/q branch_target_ex_o_reg[27]/Q -type DFF DFF
add mapped point branch_target_ex_o[28]/q branch_target_ex_o_reg[28]/Q -type DFF DFF
add mapped point branch_target_ex_o[29]/q branch_target_ex_o_reg[29]/Q -type DFF DFF
add mapped point branch_target_ex_o[30]/q branch_target_ex_o_reg[30]/Q -type DFF DFF
add mapped point branch_target_ex_o[31]/q branch_target_ex_o_reg[31]/Q -type DFF DFF
add mapped point csr_access_ex_o/q csr_access_ex_o_reg/Q -type DFF DFF
add mapped point csr_addr_ex_o[0]/q csr_addr_ex_o_reg[0]/Q -type DFF DFF
add mapped point csr_addr_ex_o[1]/q csr_addr_ex_o_reg[1]/Q -type DFF DFF
add mapped point csr_addr_ex_o[2]/q csr_addr_ex_o_reg[2]/Q -type DFF DFF
add mapped point csr_addr_ex_o[3]/q csr_addr_ex_o_reg[3]/Q -type DFF DFF
add mapped point csr_addr_ex_o[4]/q csr_addr_ex_o_reg[4]/Q -type DFF DFF
add mapped point csr_addr_ex_o[5]/q csr_addr_ex_o_reg[5]/Q -type DFF DFF
add mapped point csr_addr_ex_o[6]/q csr_addr_ex_o_reg[6]/Q -type DFF DFF
add mapped point csr_addr_ex_o[7]/q csr_addr_ex_o_reg[7]/Q -type DFF DFF
add mapped point csr_addr_ex_o[8]/q csr_addr_ex_o_reg[8]/Q -type DFF DFF
add mapped point csr_addr_ex_o[9]/q csr_addr_ex_o_reg[9]/Q -type DFF DFF
add mapped point csr_addr_ex_o[10]/q csr_addr_ex_o_reg[10]/Q -type DFF DFF
add mapped point csr_addr_ex_o[11]/q csr_addr_ex_o_reg[11]/Q -type DFF DFF
add mapped point csr_wdata_ex_o[0]/q csr_wdata_ex_o_reg[0]/Q -type DFF DFF
add mapped point csr_wdata_ex_o[1]/q csr_wdata_ex_o_reg[1]/Q -type DFF DFF
add mapped point csr_wdata_ex_o[2]/q csr_wdata_ex_o_reg[2]/Q -type DFF DFF
add mapped point csr_wdata_ex_o[3]/q csr_wdata_ex_o_reg[3]/Q -type DFF DFF
add mapped point csr_wdata_ex_o[4]/q csr_wdata_ex_o_reg[4]/Q -type DFF DFF
add mapped point csr_wdata_ex_o[5]/q csr_wdata_ex_o_reg[5]/Q -type DFF DFF
add mapped point csr_wdata_ex_o[6]/q csr_wdata_ex_o_reg[6]/Q -type DFF DFF
add mapped point csr_wdata_ex_o[7]/q csr_wdata_ex_o_reg[7]/Q -type DFF DFF
add mapped point csr_wdata_ex_o[8]/q csr_wdata_ex_o_reg[8]/Q -type DFF DFF
add mapped point csr_wdata_ex_o[9]/q csr_wdata_ex_o_reg[9]/Q -type DFF DFF
add mapped point csr_wdata_ex_o[10]/q csr_wdata_ex_o_reg[10]/Q -type DFF DFF
add mapped point csr_wdata_ex_o[11]/q csr_wdata_ex_o_reg[11]/Q -type DFF DFF
add mapped point csr_wdata_ex_o[12]/q csr_wdata_ex_o_reg[12]/Q -type DFF DFF
add mapped point csr_wdata_ex_o[13]/q csr_wdata_ex_o_reg[13]/Q -type DFF DFF
add mapped point csr_wdata_ex_o[14]/q csr_wdata_ex_o_reg[14]/Q -type DFF DFF
add mapped point csr_wdata_ex_o[15]/q csr_wdata_ex_o_reg[15]/Q -type DFF DFF
add mapped point csr_wdata_ex_o[16]/q csr_wdata_ex_o_reg[16]/Q -type DFF DFF
add mapped point csr_wdata_ex_o[17]/q csr_wdata_ex_o_reg[17]/Q -type DFF DFF
add mapped point csr_wdata_ex_o[18]/q csr_wdata_ex_o_reg[18]/Q -type DFF DFF
add mapped point csr_wdata_ex_o[19]/q csr_wdata_ex_o_reg[19]/Q -type DFF DFF
add mapped point csr_wdata_ex_o[20]/q csr_wdata_ex_o_reg[20]/Q -type DFF DFF
add mapped point csr_wdata_ex_o[21]/q csr_wdata_ex_o_reg[21]/Q -type DFF DFF
add mapped point csr_wdata_ex_o[22]/q csr_wdata_ex_o_reg[22]/Q -type DFF DFF
add mapped point csr_wdata_ex_o[23]/q csr_wdata_ex_o_reg[23]/Q -type DFF DFF
add mapped point csr_wdata_ex_o[24]/q csr_wdata_ex_o_reg[24]/Q -type DFF DFF
add mapped point csr_wdata_ex_o[25]/q csr_wdata_ex_o_reg[25]/Q -type DFF DFF
add mapped point csr_wdata_ex_o[26]/q csr_wdata_ex_o_reg[26]/Q -type DFF DFF
add mapped point csr_wdata_ex_o[27]/q csr_wdata_ex_o_reg[27]/Q -type DFF DFF
add mapped point csr_wdata_ex_o[28]/q csr_wdata_ex_o_reg[28]/Q -type DFF DFF
add mapped point csr_wdata_ex_o[29]/q csr_wdata_ex_o_reg[29]/Q -type DFF DFF
add mapped point csr_wdata_ex_o[30]/q csr_wdata_ex_o_reg[30]/Q -type DFF DFF
add mapped point csr_wdata_ex_o[31]/q csr_wdata_ex_o_reg[31]/Q -type DFF DFF
add mapped point div_busy_int/q div_busy_int_reg/Q -type DFF DFF
add mapped point fpu_busy_int/q fpu_busy_int_reg/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_a[0]/q genblk2.multiplicador_register_a_reg[0]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_a[10]/q genblk2.multiplicador_register_a_reg[10]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_a[11]/q genblk2.multiplicador_register_a_reg[11]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_a[14]/q genblk2.multiplicador_register_a_reg[14]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_a[19]/q genblk2.multiplicador_register_a_reg[19]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_a[20]/q genblk2.multiplicador_register_a_reg[20]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_a[21]/q genblk2.multiplicador_register_a_reg[21]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_a[22]/q genblk2.multiplicador_register_a_reg[22]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_a[23]/q genblk2.multiplicador_register_a_reg[23]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_a[24]/q genblk2.multiplicador_register_a_reg[24]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_a[25]/q genblk2.multiplicador_register_a_reg[25]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_a[26]/q genblk2.multiplicador_register_a_reg[26]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_a[27]/q genblk2.multiplicador_register_a_reg[27]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_a[28]/q genblk2.multiplicador_register_a_reg[28]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_a[29]/q genblk2.multiplicador_register_a_reg[29]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_a[30]/q genblk2.multiplicador_register_a_reg[30]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_a[31]/q genblk2.multiplicador_register_a_reg[31]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_b[1]/q genblk2.multiplicador_register_b_reg[1]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_b[2]/q genblk2.multiplicador_register_b_reg[2]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_b[3]/q genblk2.multiplicador_register_b_reg[3]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_b[4]/q genblk2.multiplicador_register_b_reg[4]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_b[5]/q genblk2.multiplicador_register_b_reg[5]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_b[6]/q genblk2.multiplicador_register_b_reg[6]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_b[7]/q genblk2.multiplicador_register_b_reg[7]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_b[8]/q genblk2.multiplicador_register_b_reg[8]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_b[9]/q genblk2.multiplicador_register_b_reg[9]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_b[10]/q genblk2.multiplicador_register_b_reg[10]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_b[11]/q genblk2.multiplicador_register_b_reg[11]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_b[12]/q genblk2.multiplicador_register_b_reg[12]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_b[13]/q genblk2.multiplicador_register_b_reg[13]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_b[14]/q genblk2.multiplicador_register_b_reg[14]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_b[16]/q genblk2.multiplicador_register_b_reg[16]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_b[18]/q genblk2.multiplicador_register_b_reg[18]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_b[20]/q genblk2.multiplicador_register_b_reg[20]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_b[22]/q genblk2.multiplicador_register_b_reg[22]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_b[24]/q genblk2.multiplicador_register_b_reg[24]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_b[26]/q genblk2.multiplicador_register_b_reg[26]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_b[28]/q genblk2.multiplicador_register_b_reg[28]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_b[30]/q genblk2.multiplicador_register_b_reg[30]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_b[31]/q genblk2.multiplicador_register_b_reg[31]/Q -type DFF DFF
add mapped point genblk2.multiplicador/resultado[0]/q genblk2.multiplicador_resultado_reg[0]/Q -type DFF DFF
add mapped point genblk2.multiplicador/resultado[1]/q genblk2.multiplicador_resultado_reg[1]/Q -type DFF DFF
add mapped point genblk2.multiplicador/resultado[2]/q genblk2.multiplicador_resultado_reg[2]/Q -type DFF DFF
add mapped point genblk2.multiplicador/resultado[3]/q genblk2.multiplicador_resultado_reg[3]/Q -type DFF DFF
add mapped point genblk2.multiplicador/resultado[4]/q genblk2.multiplicador_resultado_reg[4]/Q -type DFF DFF
add mapped point genblk2.multiplicador/resultado[5]/q genblk2.multiplicador_resultado_reg[5]/Q -type DFF DFF
add mapped point genblk2.multiplicador/resultado[6]/q genblk2.multiplicador_resultado_reg[6]/Q -type DFF DFF
add mapped point genblk2.multiplicador/resultado[7]/q genblk2.multiplicador_resultado_reg[7]/Q -type DFF DFF
add mapped point genblk2.multiplicador/resultado[8]/q genblk2.multiplicador_resultado_reg[8]/Q -type DFF DFF
add mapped point genblk2.multiplicador/resultado[9]/q genblk2.multiplicador_resultado_reg[9]/Q -type DFF DFF
add mapped point genblk2.multiplicador/resultado[10]/q genblk2.multiplicador_resultado_reg[10]/Q -type DFF DFF
add mapped point genblk2.multiplicador/resultado[11]/q genblk2.multiplicador_resultado_reg[11]/Q -type DFF DFF
add mapped point genblk2.multiplicador/resultado[12]/q genblk2.multiplicador_resultado_reg[12]/Q -type DFF DFF
add mapped point genblk2.multiplicador/resultado[13]/q genblk2.multiplicador_resultado_reg[13]/Q -type DFF DFF
add mapped point genblk2.multiplicador/resultado[14]/q genblk2.multiplicador_resultado_reg[14]/Q -type DFF DFF
add mapped point genblk2.multiplicador/resultado[15]/q genblk2.multiplicador_resultado_reg[15]/Q -type DFF DFF
add mapped point genblk2.multiplicador/resultado[16]/q genblk2.multiplicador_resultado_reg[16]/Q -type DFF DFF
add mapped point genblk2.multiplicador/resultado[17]/q genblk2.multiplicador_resultado_reg[17]/Q -type DFF DFF
add mapped point genblk2.multiplicador/resultado[18]/q genblk2.multiplicador_resultado_reg[18]/Q -type DFF DFF
add mapped point genblk2.multiplicador/resultado[19]/q genblk2.multiplicador_resultado_reg[19]/Q -type DFF DFF
add mapped point genblk2.multiplicador/resultado[20]/q genblk2.multiplicador_resultado_reg[20]/Q -type DFF DFF
add mapped point genblk2.multiplicador/resultado[21]/q genblk2.multiplicador_resultado_reg[21]/Q -type DFF DFF
add mapped point genblk2.multiplicador/resultado[22]/q genblk2.multiplicador_resultado_reg[22]/Q -type DFF DFF
add mapped point genblk2.multiplicador/resultado[23]/q genblk2.multiplicador_resultado_reg[23]/Q -type DFF DFF
add mapped point genblk2.multiplicador/resultado[24]/q genblk2.multiplicador_resultado_reg[24]/Q -type DFF DFF
add mapped point genblk2.multiplicador/resultado[25]/q genblk2.multiplicador_resultado_reg[25]/Q -type DFF DFF
add mapped point genblk2.multiplicador/resultado[26]/q genblk2.multiplicador_resultado_reg[26]/Q -type DFF DFF
add mapped point genblk2.multiplicador/resultado[27]/q genblk2.multiplicador_resultado_reg[27]/Q -type DFF DFF
add mapped point genblk2.multiplicador/resultado[28]/q genblk2.multiplicador_resultado_reg[28]/Q -type DFF DFF
add mapped point genblk2.multiplicador/resultado[29]/q genblk2.multiplicador_resultado_reg[29]/Q -type DFF DFF
add mapped point genblk2.multiplicador/resultado[30]/q genblk2.multiplicador_resultado_reg[30]/Q -type DFF DFF
add mapped point genblk2.multiplicador/resultado[31]/q genblk2.multiplicador_resultado_reg[31]/Q -type DFF DFF
add mapped point genblk2.multiplicador/state[0]/q genblk2.multiplicador_state_reg[0]/Q -type DFF DFF
add mapped point genblk2.multiplicador/state[1]/q genblk2.multiplicador_state_reg[1]/Q -type DFF DFF
add mapped point is_branch_ex/q is_branch_ex_reg/Q -type DFF DFF
add mapped point mem_data_type_ex_o[0]/q mem_data_type_ex_o_reg[0]/Q -type DFF DFF
add mapped point mem_data_type_ex_o[1]/q mem_data_type_ex_o_reg[1]/Q -type DFF DFF
add mapped point mem_sign_extend_ex_o/q mem_sign_extend_ex_o_reg/Q -type DFF DFF
add mapped point mem_wdata_ex_o[0]/q mem_wdata_ex_o_reg[0]/Q -type DFF DFF
add mapped point mem_wdata_ex_o[1]/q mem_wdata_ex_o_reg[1]/Q -type DFF DFF
add mapped point mem_wdata_ex_o[2]/q mem_wdata_ex_o_reg[2]/Q -type DFF DFF
add mapped point mem_wdata_ex_o[3]/q mem_wdata_ex_o_reg[3]/Q -type DFF DFF
add mapped point mem_wdata_ex_o[4]/q mem_wdata_ex_o_reg[4]/Q -type DFF DFF
add mapped point mem_wdata_ex_o[5]/q mem_wdata_ex_o_reg[5]/Q -type DFF DFF
add mapped point mem_wdata_ex_o[6]/q mem_wdata_ex_o_reg[6]/Q -type DFF DFF
add mapped point mem_wdata_ex_o[7]/q mem_wdata_ex_o_reg[7]/Q -type DFF DFF
add mapped point mem_wdata_ex_o[8]/q mem_wdata_ex_o_reg[8]/Q -type DFF DFF
add mapped point mem_wdata_ex_o[9]/q mem_wdata_ex_o_reg[9]/Q -type DFF DFF
add mapped point mem_wdata_ex_o[10]/q mem_wdata_ex_o_reg[10]/Q -type DFF DFF
add mapped point mem_wdata_ex_o[11]/q mem_wdata_ex_o_reg[11]/Q -type DFF DFF
add mapped point mem_wdata_ex_o[12]/q mem_wdata_ex_o_reg[12]/Q -type DFF DFF
add mapped point mem_wdata_ex_o[13]/q mem_wdata_ex_o_reg[13]/Q -type DFF DFF
add mapped point mem_wdata_ex_o[14]/q mem_wdata_ex_o_reg[14]/Q -type DFF DFF
add mapped point mem_wdata_ex_o[15]/q mem_wdata_ex_o_reg[15]/Q -type DFF DFF
add mapped point mem_wdata_ex_o[16]/q mem_wdata_ex_o_reg[16]/Q -type DFF DFF
add mapped point mem_wdata_ex_o[17]/q mem_wdata_ex_o_reg[17]/Q -type DFF DFF
add mapped point mem_wdata_ex_o[18]/q mem_wdata_ex_o_reg[18]/Q -type DFF DFF
add mapped point mem_wdata_ex_o[19]/q mem_wdata_ex_o_reg[19]/Q -type DFF DFF
add mapped point mem_wdata_ex_o[20]/q mem_wdata_ex_o_reg[20]/Q -type DFF DFF
add mapped point mem_wdata_ex_o[21]/q mem_wdata_ex_o_reg[21]/Q -type DFF DFF
add mapped point mem_wdata_ex_o[22]/q mem_wdata_ex_o_reg[22]/Q -type DFF DFF
add mapped point mem_wdata_ex_o[23]/q mem_wdata_ex_o_reg[23]/Q -type DFF DFF
add mapped point mem_wdata_ex_o[24]/q mem_wdata_ex_o_reg[24]/Q -type DFF DFF
add mapped point mem_wdata_ex_o[25]/q mem_wdata_ex_o_reg[25]/Q -type DFF DFF
add mapped point mem_wdata_ex_o[26]/q mem_wdata_ex_o_reg[26]/Q -type DFF DFF
add mapped point mem_wdata_ex_o[27]/q mem_wdata_ex_o_reg[27]/Q -type DFF DFF
add mapped point mem_wdata_ex_o[28]/q mem_wdata_ex_o_reg[28]/Q -type DFF DFF
add mapped point mem_wdata_ex_o[29]/q mem_wdata_ex_o_reg[29]/Q -type DFF DFF
add mapped point mem_wdata_ex_o[30]/q mem_wdata_ex_o_reg[30]/Q -type DFF DFF
add mapped point mem_wdata_ex_o[31]/q mem_wdata_ex_o_reg[31]/Q -type DFF DFF
add mapped point mul_busy_int/q mul_busy_int_reg/Q -type DFF DFF
add mapped point pc_ex_o[0]/q pc_ex_o_reg[0]/Q -type DFF DFF
add mapped point pc_ex_o[1]/q pc_ex_o_reg[1]/Q -type DFF DFF
add mapped point pc_ex_o[2]/q pc_ex_o_reg[2]/Q -type DFF DFF
add mapped point pc_ex_o[3]/q pc_ex_o_reg[3]/Q -type DFF DFF
add mapped point pc_ex_o[4]/q pc_ex_o_reg[4]/Q -type DFF DFF
add mapped point pc_ex_o[5]/q pc_ex_o_reg[5]/Q -type DFF DFF
add mapped point pc_ex_o[6]/q pc_ex_o_reg[6]/Q -type DFF DFF
add mapped point pc_ex_o[7]/q pc_ex_o_reg[7]/Q -type DFF DFF
add mapped point pc_ex_o[8]/q pc_ex_o_reg[8]/Q -type DFF DFF
add mapped point pc_ex_o[9]/q pc_ex_o_reg[9]/Q -type DFF DFF
add mapped point pc_ex_o[10]/q pc_ex_o_reg[10]/Q -type DFF DFF
add mapped point pc_ex_o[11]/q pc_ex_o_reg[11]/Q -type DFF DFF
add mapped point pc_ex_o[12]/q pc_ex_o_reg[12]/Q -type DFF DFF
add mapped point pc_ex_o[13]/q pc_ex_o_reg[13]/Q -type DFF DFF
add mapped point pc_ex_o[14]/q pc_ex_o_reg[14]/Q -type DFF DFF
add mapped point pc_ex_o[15]/q pc_ex_o_reg[15]/Q -type DFF DFF
add mapped point pc_ex_o[16]/q pc_ex_o_reg[16]/Q -type DFF DFF
add mapped point pc_ex_o[17]/q pc_ex_o_reg[17]/Q -type DFF DFF
add mapped point pc_ex_o[18]/q pc_ex_o_reg[18]/Q -type DFF DFF
add mapped point pc_ex_o[19]/q pc_ex_o_reg[19]/Q -type DFF DFF
add mapped point pc_ex_o[20]/q pc_ex_o_reg[20]/Q -type DFF DFF
add mapped point pc_ex_o[21]/q pc_ex_o_reg[21]/Q -type DFF DFF
add mapped point pc_ex_o[22]/q pc_ex_o_reg[22]/Q -type DFF DFF
add mapped point pc_ex_o[23]/q pc_ex_o_reg[23]/Q -type DFF DFF
add mapped point pc_ex_o[24]/q pc_ex_o_reg[24]/Q -type DFF DFF
add mapped point pc_ex_o[25]/q pc_ex_o_reg[25]/Q -type DFF DFF
add mapped point pc_ex_o[26]/q pc_ex_o_reg[26]/Q -type DFF DFF
add mapped point pc_ex_o[27]/q pc_ex_o_reg[27]/Q -type DFF DFF
add mapped point pc_ex_o[28]/q pc_ex_o_reg[28]/Q -type DFF DFF
add mapped point pc_ex_o[29]/q pc_ex_o_reg[29]/Q -type DFF DFF
add mapped point pc_ex_o[30]/q pc_ex_o_reg[30]/Q -type DFF DFF
add mapped point pc_ex_o[31]/q pc_ex_o_reg[31]/Q -type DFF DFF
add mapped point pc_source_ex_o[0]/q pc_source_ex_o_reg[0]/Q -type DFF DFF
add mapped point pc_source_ex_o[1]/q pc_source_ex_o_reg[1]/Q -type DFF DFF
add mapped point rd_addr_ex_o[0]/q rd_addr_ex_o_reg[0]/Q -type DFF DFF
add mapped point rd_addr_ex_o[1]/q rd_addr_ex_o_reg[1]/Q -type DFF DFF
add mapped point rd_addr_ex_o[2]/q rd_addr_ex_o_reg[2]/Q -type DFF DFF
add mapped point rd_addr_ex_o[3]/q rd_addr_ex_o_reg[3]/Q -type DFF DFF
add mapped point rd_addr_ex_o[4]/q rd_addr_ex_o_reg[4]/Q -type DFF DFF
add mapped point rd_dst_bank_ex_o/q rd_dst_bank_ex_o_reg/Q -type DFF DFF
add mapped point csr_op_ex_o[0]/q csr_op_ex_o_reg[0]/Q -type DFF DFF
add mapped point csr_op_ex_o[1]/q csr_op_ex_o_reg[1]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_a[1]/q genblk2.multiplicador_register_a_reg[1]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_a[2]/q genblk2.multiplicador_register_a_reg[2]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_a[3]/q genblk2.multiplicador_register_a_reg[3]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_a[4]/q genblk2.multiplicador_register_a_reg[4]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_a[5]/q genblk2.multiplicador_register_a_reg[5]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_a[6]/q genblk2.multiplicador_register_a_reg[6]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_a[7]/q genblk2.multiplicador_register_a_reg[7]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_a[8]/q genblk2.multiplicador_register_a_reg[8]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_a[9]/q genblk2.multiplicador_register_a_reg[9]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_a[12]/q genblk2.multiplicador_register_a_reg[12]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_a[13]/q genblk2.multiplicador_register_a_reg[13]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_a[15]/q genblk2.multiplicador_register_a_reg[15]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_a[16]/q genblk2.multiplicador_register_a_reg[16]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_a[17]/q genblk2.multiplicador_register_a_reg[17]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_a[18]/q genblk2.multiplicador_register_a_reg[18]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_b[0]/q genblk2.multiplicador_register_b_reg[0]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_b[15]/q genblk2.multiplicador_register_b_reg[15]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_b[17]/q genblk2.multiplicador_register_b_reg[17]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_b[19]/q genblk2.multiplicador_register_b_reg[19]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_b[21]/q genblk2.multiplicador_register_b_reg[21]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_b[23]/q genblk2.multiplicador_register_b_reg[23]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_b[25]/q genblk2.multiplicador_register_b_reg[25]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_b[27]/q genblk2.multiplicador_register_b_reg[27]/Q -type DFF DFF
add mapped point genblk2.multiplicador/register_b[29]/q genblk2.multiplicador_register_b_reg[29]/Q -type DFF DFF
add mapped point mem_wen_ex_o/q mem_wen_ex_o_reg/Q -type DFF DFF
add mapped point reg_alu_wen_ex_o/q reg_alu_wen_ex_o_reg/Q -type DFF DFF
add mapped point reg_mem_wen_ex_o/q reg_mem_wen_ex_o_reg/Q -type DFF DFF
add mapped point valid_ex_o/q valid_ex_o_reg/Q -type DFF DFF



//Black Boxes
add mapped point alu_inst alu_inst -type BBOX BBOX
add mapped point genblk1.fpu_inst genblk1.fpu_inst -type BBOX BBOX
add mapped point genblk2.divisor genblk2.divisor -type BBOX BBOX



//Empty Modules as Blackboxes
