
// Generated by Cadence Genus(TM) Synthesis Solution 25.10-p002_1
// Generated on: Jul  1 2025 19:21:24 PDT (Jul  2 2025 02:21:24 UTC)

// Verification Directory fv/counter 

module counter(clk, rst, count, SE, scan_in, scan_out);
  input clk, rst, SE, scan_in;
  output [7:0] count;
  output scan_out;
  wire clk, rst, SE, scan_in;
  wire [7:0] count;
  wire scan_out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13;
  SDFFRHQX1 \count_reg[7] (.RN (rst), .CK (clk), .D (n_13), .SI
       (count[6]), .SE (SE), .Q (count[7]));
  SDFFRHQX1 \count_reg[6] (.RN (rst), .CK (clk), .D (n_12), .SI
       (count[5]), .SE (SE), .Q (count[6]));
  XNOR2X1 g416__2398(.A (count[7]), .B (n_11), .Y (n_13));
  SDFFRHQX1 \count_reg[5] (.RN (rst), .CK (clk), .D (n_9), .SI
       (count[4]), .SE (SE), .Q (count[5]));
  OA21X1 g418__5107(.A0 (count[6]), .A1 (n_10), .B0 (n_11), .Y (n_12));
  SDFFRHQX1 \count_reg[4] (.RN (rst), .CK (clk), .D (n_8), .SI
       (count[3]), .SE (SE), .Q (count[4]));
  NAND2X1 g420__6260(.A (count[6]), .B (n_10), .Y (n_11));
  XNOR2X1 g421__4319(.A (count[5]), .B (n_7), .Y (n_9));
  SDFFRHQX1 \count_reg[3] (.RN (rst), .CK (clk), .D (n_5), .SI
       (count[2]), .SE (SE), .Q (count[3]));
  SDFFRHQX1 \count_reg[2] (.RN (rst), .CK (clk), .D (n_3), .SI
       (count[1]), .SE (SE), .Q (count[2]));
  OA21X1 g424__8428(.A0 (count[4]), .A1 (n_6), .B0 (n_7), .Y (n_8));
  NOR2BX1 g423__5526(.AN (count[5]), .B (n_7), .Y (n_10));
  NAND2X1 g426__6783(.A (count[4]), .B (n_6), .Y (n_7));
  XNOR2X1 g427__3680(.A (count[3]), .B (n_4), .Y (n_5));
  NOR2BX1 g429__1617(.AN (count[3]), .B (n_4), .Y (n_6));
  OA21X1 g430__2802(.A0 (count[2]), .A1 (n_2), .B0 (n_4), .Y (n_3));
  SDFFRHQX1 \count_reg[1] (.RN (rst), .CK (clk), .D (n_1), .SI
       (count[0]), .SE (SE), .Q (count[1]));
  NAND2X1 g432__1705(.A (count[2]), .B (n_2), .Y (n_4));
  SDFFRHQX1 \count_reg[0] (.RN (rst), .CK (clk), .D (n_0), .SI
       (scan_in), .SE (SE), .Q (count[0]));
  ADDHX1 g433__5122(.A (count[0]), .B (count[1]), .CO (n_2), .S (n_1));
  INVX1 g435(.A (count[0]), .Y (n_0));
  BUFX20 rm_assigns_buf_scan_out(.A (count[7]), .Y (scan_out));
endmodule

